apiVersion: v1
kind: Namespace
metadata:
  name: jquery-static
---
apiVersion: v1
kind: Service
metadata:
  name: jquery-static-svc
  namespace: jquery-static
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: jquery-static-ingress
 namespace: jquery-static
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: jquery-static.kirthinareshtech.xyz
   http:
     paths:
     - path:
       backend:
         serviceName: jquery-static-svc
         servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: jquery-static
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 652157035123.dkr.ecr.us-east-2.amazonaws.com/jquery-static:number
        ports:
        - containerPort: 80
---